

#         Powered by TabooLib 5.0         #


database:
  use: LOCAL
  source:
    SQL:
      host: localhost
      port: 3306
      user: root
      password: root
      database: test
      table: chemdah
    MongoDB:
      client: 'mongodb://localhost:3308'
      database: test
      collection: chemdah

default-stats:
  stay: 100
  style: SOLID
  color: WHITE
  content: '&3[{name}] &7{value}/{target} &f[{percent}%]'

default-track:
  message: '&7Tracking &3[{name}]&7... Click to cancel.'
  mark:
    value: true
    type: CLOUD
    size: 0.05
    count: 500
    distance:
      min: 32
      max: 64
    period: 2
  navigation:
    value: true
    sync: true
    type: CRIT
    size:
      x: 0.2
      y: 0.2
    count: 20
    content:
      - '&a[ - {name} - ]'
      - '({distance}m)'
    distance:
      min: 3
      max: 64
    period: 40
  scoreboard:
    value: true
    length: 64
    content:
      - '&6&lCHEMDAH TRACKS'
      - - ''
        - ' &f{name}:'
        - ' {description}'
      - ''